Fix test failure caused by .NET 8 upgrade
The test failed with the following:

    4.221 /app/BaseApi.Tests/V1/Infrastructure/ExampleContextTests.cs(21,20): error CS0117: 'Assert' does not contain a definition for 'AreEqual' [/app/BaseApi.Tests/BaseApi.Tests.csproj]

There's a new format for test assertions, which the code has been updated to use. In existing projects this can be fixed by either updating to the modern format or by using ClassicAssert, which suports the legacy API