Fix test failure cause by .NET 8 upgrade
This test failed with the following error:

    4.413 /app/BaseApi.Tests/V1/Controllers/BaseControllerTests.cs(44,13): error ASP0019: Use IHeaderDictionary.Append or the indexer to append or set headers. IDictionary.Add will throw an ArgumentException when attempting to add a duplicate key. (https://aka.ms/aspnet/analyzers) [/app/BaseApi.Tests/BaseApi.Tests.csproj]

The error is resolved by using Append as suggested